# Site settings
title: Rob Hilgefort Resume
description: Rob Hilgefort Resume
favicon: /resume/assets/img/avatar.jpg
baseurl: ""
url: http://resume.rob.hilgefort.com
rss_url: /resume/pages/atom.xml

# Build settings
markdown: kramdown

# Author settings
author:
  gavatar: /assets/img/avatar.jpg
  name: Rob Hilgefort
  title: Lead Software Developer
  address: Cincinnati, OH
  email: rjhilgefort@gmail.com
  link: http://rob.hilgefort.me
  github: rjhilgefort
  linkedin: rjhilgefort
  twitter: rjhilgefort

  workHistory:
    - work1:
      company: Finzsoft Solutions Ltd
      location: Auckland, New Zealand
      title: Java Developer
      started: 2014
      duration: (2014 - Present)
      description: something

    - work2:
      company: Agfa HealthCare
      location: Shanghai, China
      title: Java Developer
      started: 2012
      duration: (2012 - 2014)
      description: something

    - work3:
      company: Citigroup Services and Technology (China) Limited
      location: Shanghai, China
      title: Java Developer
      started: 2009
      duration: (2009 - 2012)
      description: something

  educationHistory:
    - college:
      organization: "University of Kentucky"
      # location: Lexington, Ky
      degree: "Bachelor"
      major: "Philosophy"
      # minor:
      #   - Computer Science
      #   - Psychology
      started: 2005
      # ended: 2010 # When implemented, remove `duration`
      duration: "(2005 - 2010)"
      # description: "" # non-existance would do something special to bullets styling
      bullets:
        - relatedCoursework:
          description: "Related Coursework: Web Programming, Algorithm Design/Analysis, Software Engineer Training"
          skills: "Java, CGI, Perl, C#, JavaScript, PHP, MySQL"

  programmingSkills:
    - javascript:
      name: "JavaScript"
      percentage: 100%

  languages:
    - language1:
      name: English
      proficiency: Native
