# Site settings
title: Rob Hilgefort Resume
description: Rob Hilgefort Resume
favicon: /resume/assets/img/avatar.jpg
baseurl: ""
url: http://resume.rob.hilgefort.com
rss_url: /resume/pages/atom.xml

# Build settings
markdown: kramdown

# Author settings
author:
  gavatar: /assets/img/avatar.jpg
  name: Rob Hilgefort
  title: Lead Software Developer
  address: Cincinnati, OH
  email: rjhilgefort@gmail.com
  link: http://rob.hilgefort.me
  github: rjhilgefort
  linkedin: rjhilgefort
  twitter: rjhilgefort

  workHistory:
    - work1:
      name: Finzsoft Solutions Ltd
      location: Auckland, New Zealand
      title: Java Developer
      started: 2014
      ended: Present
      description: something

    - work2:
      name: Agfa HealthCare
      location: Shanghai, China
      title: Java Developer
      started: 2012
      ended: 2014
      description: something

    - work3:
      name: Citigroup Services and Technology (China) Limited
      location: Shanghai, China
      title: Java Developer
      started: 2009
      ended: 2012
      description: something

  educationHistory:
    - UK:
      name: "University of Kentucky"
      location: "Lexington, Ky"
      degree: "Bachelor"
      major: "Philosophy"
      # minor:
      #   - Computer Science
      #   - Psychology
      started: 2005
      ended: 2010
      description: "Something amazing" # non-existance would do something special to bullets styling
      # bullets:
      #   - relatedCoursework:
      #     description: "Related Coursework: Web Programming, Algorithm Design/Analysis, Software Engineer Training"
      #     skills: "Java, CGI, Perl, C#, JavaScript, PHP, MySQL"

  programmingSkills:
    - name: "JavaScript"
      percentage: 100
    - name: "Jekyll"
      percentage: 20
      # url: "www.foo.com" # TODO: allow for optional links
    - name: "Ruby"
      percentage: 15
      # url: "www.foo.com" # TODO: allow for optional links

  # languages:
  #   - language1:
  #     name: English
  #     proficiency: Native
